FROM jupyter/base-notebook:python-3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git && apt-get clean && rm -rf /var/lib/apt/lists/*
USER ${NB_UID}

COPY requirements-jupyter.txt /tmp/requirements-jupyter.txt
RUN pip install --no-cache-dir -r /tmp/requirements-jupyter.txt

WORKDIR /home/jovyan
